/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pun1shR (https://sketchfab.com/pun1shr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arrow-bd395aa897ad45a19505f63d82519df3
Title: arrow
*/

import { useRef } from 'react';
import { useGLTF, Text3D, Center } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Arrow({...props}) {
  const { nodes, materials } = useGLTF('/models/arrow/scene.gltf');
  const arrowRef = useRef();
  const scrollRef = useRef();

  useFrame(() => {
      if (arrowRef.current) {
        arrowRef.current.rotation.z += 0.01;
      }
  });

  useFrame(() => {
    if (scrollRef.current) {
      scrollRef.current.rotation.y += 0.01;
    }
  });

  return (
    <group {...props} dispose={null}>
      <Center ref={scrollRef} position={[0.01, 0.18, -0.1]} rotation={[0, -3.1, 0.1]} scale={0.08}>
        <Text3D letterSpacing={-0.06} size={0.5} font="fonts/Inter_Bold.json">
            scroll
            <meshStandardMaterial color="white" />
        </Text3D>
      </Center>
      <group ref={arrowRef} rotation={[-Math.PI / 2, 0.099, -Math.PI / 2]} scale={0.061}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials['tex-global']}
            position={[0, -1, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/arrow/scene.gltf')
