/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rude Randal (https://sketchfab.com/Rude_Randal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-astronaut-5bb793a440164595ac4cb605822b2d88
Title: Little Astronaut
*/

import { useRef } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/astro/scene.gltf');
  const groupRef = useRef();

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.x += 0.01; // Adjust the rotation speed as needed
    }
  });

  return (
    <Float floatIntensity={5} speed={1}>
      <group ref={groupRef} {...props} dispose={null}>
        <ambientLight intensity={2} />
        <group>
          <group rotation={[20, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.Character_Texture}
              position={[0, 1.636, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Character_Texture}
              position={[0, 3.106, 0.123]}
              scale={[1.468, 1.531, 1.494]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Character_Texture}
              position={[0, 1.835, -1.056]}
              scale={[0.776, 0.394, 0.394]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.Character_Texture}
              position={[0, 1.91, -1.041]}
            />
          </group>
        </group>
      </group>
    </Float>
  );
}

useGLTF.preload('/models/astro/scene.gltf');
