/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF, useVideoTexture } from '@react-three/drei';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

export default function Mac(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/mac/scene.glb');

  // eslint-disable-next-line react/prop-types
  const texture = useVideoTexture(props.texture ? props.texture : '/models/phone/project1.mp4');

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [texture]);

  return (
    <group ref={group} scale={0.02} position={[0,0.5,0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stand_LightBlue_0.geometry}
          material={materials.LightBlue}
        />
        <group position={[0.032, 0, 0.387]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rotate_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rotate_Metal2_0.geometry}
            material={materials.Metal2}
          />
          <group position={[-0.03, 0, -0.387]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_DarkBlue_0.geometry}
              material={materials.DarkBlue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_LightBlue_0.geometry}
              material={materials.LightBlue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Black_0.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_White_0.geometry}
              material={materials.White}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Screen_0.geometry}
            >
              <meshBasicMaterial map={texture} toneMapped={false} />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Chrome_0.geometry}
              material={materials.Chrome}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_CamBlack_0.geometry}
              material={materials['Cam.Black']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Lens_0.geometry}
              material={materials.Lens}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Glass_0.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Black001_0.geometry}
              material={materials['Black.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Yellow_0.geometry}
              material={materials.Yellow}
            />
          </group>
        </group>
      </group>
    </group>
  )
};

useGLTF.preload('/models/mac/scene.glb');
